/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flight;

import java.awt.event.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Koustav Pain
 */
public class SearchPage extends javax.swing.JFrame {
    
    public String srcNM="-",day;
    public Seats ss[]=new Seats[100];
    public PersistenceManager pm=new PersistenceManager();
    public SpiceJet sj[];
    public SilkAir sa[];
    public int m,n;
    SwingDisplayManager dm;
    /**
     * Creates new form SearchPage
     */
    public SearchPage(String args[],SwingDisplayManager dm) {
        initComponents();
        this.dm=dm;
        sj=pm.readSpiceJet(args[0]);
        sa=pm.readSilkAir(args[1]);
        SimpleDateFormat sdf = new SimpleDateFormat("d-MMM-yyyy");
        try {
            if(sdf.parse(sj[0].effecTill).before(sdf.parse(sa[0].effecFrom))&&sdf.parse(sj[0].effecTill).before(sdf.parse(sa[0].effecTill))||sdf.parse(sj[0].effecFrom).after(sdf.parse(sa[0].effecFrom))&&sdf.parse(sj[0].effecFrom).after(sdf.parse(sa[0].effecTill))){
                JOptionPane.showMessageDialog(null, "Incompatible dates, please check input data");
                System.exit(0);
            }
        } catch (ParseException ex) {
            Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
        jComboBox1.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e) {        
            if (e.getStateChange() == ItemEvent.SELECTED) {
                      JComboBox cb = (JComboBox)e.getSource();
                      srcNM = new String((String)cb.getSelectedItem());
                      //System.out.print(srcNM+" ");
                  }
          }
        });//OR .addActionListener(this);
       /* jComboBox3.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e) {        
            if (e.getStateChange() == ItemEvent.SELECTED) {
                      JComboBox cb = (JComboBox)e.getSource();
                      n = Integer.parseInt((String)cb.getSelectedItem());                      
                      //System.out.print(n+" ");
                  }
          }
        });*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Blue Airline ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 30, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flight/download (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 80, 60);

        jLabel3.setText("Date :-");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 180, 90, 20);

        jLabel5.setText("Source :-");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 90, 60, 30);

        jLabel6.setText("Destination :-");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 130, 80, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 250, 100, 30);

        jDateChooser1.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(220, 180, 120, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Delhi", "Mumbai", "Pune" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(220, 100, 100, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Singapore" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(220, 140, 100, 20);

        jLabel7.setText("No. of Tickets :-");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 210, 90, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(220, 210, 100, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flight/checkin1.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 80, 440, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        int i;
    
            n=Integer.parseInt(jComboBox3.getSelectedItem().toString());
            day=new String(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());//getSelectedItem().toString();
           // System.out.print(day+" d");           
            if(srcNM.equalsIgnoreCase("-")||day.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Enter the Source & Date");
                return;
            }
            m=-1;
            
            for(i=0;i<Seats.sz;i++)
            {
                if((day).equalsIgnoreCase(ss[i].day))
                {m=i;break;}
                
            }
            if(m==-1){
                ss[Seats.sz]=new Seats(Flight.sz,day);
                m=Seats.sz;
                Seats.sz++;
                }
            
            //System.out.println(m);
            dm.displayFlightListing(srcNM,day,sj,sa,ss[m],n);
            //new Frame2(srcNM,day,sj,sa,ss[m]).setVisible(true);
            
           // this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    


}
